tx-pts-dai/github-workflows

.github/workflows/docker-push-ecr.yaml, .github/workflows/tf-deploy-basic.yaml, .pre-commit-config.yaml
The current state is not working.
I found that the default branch is passed in the github.event 
https://github.com/swibrow/actions-playground/pull/2
and the event context is always in push events. 
https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
=> Fix default branch

.github/workflows/_test-workflows.yaml, .github/workflows/docker-build-push-ecr.yaml
It's faster than using build and push separately because upload/download artifact actions are not always a needed overhead
=> feat: add docker-build-push-ecr workflow

.github/workflows/_test-workflows.yaml, .github/workflows/tf-deploy-basic.yaml
- Fix the terraform init argument when tf_state_key and tf_state_bucket are not all specified
- Make terraform init fail instead of asking for missing parameters
- Make the "aws_role_name" optional
- Echo the terraform init command
- typo
=> fix: terraform init arguments

.github/workflows/lambda-build-node.yaml
Installing a local npm package creates a symlink and when the module folder was moved the symlink was also removed
=> copy modules into nodejs folder so symlinks are still valid

.github/workflows/tf-deploy-basic.yaml
Use a more generic way to pass arguments to terraform init (`tf_backend_configs` input).
the current `tf_state_bucket` and `tf_state_key` inputs are still kept but to discuss if we want to support both way or not ?
=> replace tf init parameters 

.github/workflows/_test-docker.yaml, .github/workflows/docker-build-push-ecr.yaml, README.md, tests/docker/secrets.Dockerfile
Enabling `docker_secrets` to be passed downstream allows for secrets to be used at build-time (e.g. to clone a private repo or to serve a token to a private NPM/Python registry)
Usage:
```yaml
test_docker_build_secrets:
uses: ./.github/workflows/docker-build-push-ecr.yaml
secrets:
docker_secrets: |
SECRET_TOKEN="S€cReT1!"
with:
[...]
```
=> feat: add possibility to configure the Dockerfile path separately and support Docker secrets

.github/workflows/_test-tf-dflook.yaml, .github/workflows/tf-dflook-apply.yaml, .github/workflows/tf-dflook-cleanup.yaml, .github/workflows/tf-dflook-feature.yaml, .github/workflows/tf-dflook-plan.yaml
Installs aws cli as an extra step for plan, apply and destroy jobs
```
Tue, 09 Apr 2024 15:13:34 GMT
Executing TERRAFORM_PRE_RUN
Tue, 09 Apr 2024 15:13:34 GMT
Executing init commands specified in 'TERRAFORM_PRE_RUN' environment variable
Tue, 09 Apr 2024 15:13:35 GMT
::stop-commands::***
Tue, 09 Apr 2024 15:13:35 GMT
+ curl https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip -o awscliv2.zip
Tue, 09 Apr 2024 15:13:35 GMT
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Tue, 09 Apr 2024 15:13:35 GMT
Dload  Upload   Total   Spent    Left  Speed
Tue, 09 Apr 2024 15:13:35 GMT
Tue, 09 Apr 2024 15:13:35 GMT
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
Tue, 09 Apr 2024 15:13:35 GMT
100 57.6M  100 57.6M    0     0   124M      0 …
```
=> fix: install aws cli for dflook apply jobs

.github/workflows/tf-cleanup.yaml, .github/workflows/tf-feature.yaml, docs/README-tf-deploy.md
The issue is that when we call this workflow on workflow_dispatch we do not have `github.head_ref` therefore I would like to add the possibility to inject the `tf_workspace`.
Example:
https://github.com/tx-pts-dai/terraform-aws-kubernetes-platform/actions/runs/8880678914/job/24381276096
Should we add this also on other workflows to support all the workflow triggers?
For context, here is the doc for `github.head_ref`
> github.head_ref	string	
> The head_ref or source branch of the pull request in a workflow run. This property is only available when the event that triggers a workflow run is either pull_request or pull_request_target.
=> Allow to specify tf workspace

.github/workflows/tf-plan.yaml
This is quite a nasty error that has been reported for quite a long time on different github issues. The issue is that there is that the github runners variables such as GITHUB_STEP_SUMMARY has a max size of whatever shell/bash limitations. As example, the error 
`{{An error occurred trying to start process '/usr/bin/bash' with working directory '/home/runner/work/fum-3137/fum-3137'. Argument list too long}}`
can be reproduced with any simple bash command such as tail, with a too long plan as an argument.
The solution I came up with was to trim the SUMMARY to max 120’000 chars (I think it’s about the right threshold). This way it also works for verrrrrry long plans. I tested with different values from 20’000 up to 100’000 it seems too low, for 150’000 it crashes as well with the same …
=> Fum 3196 too big plan

renovate.json
Central renovate config
https://github.com/tx-pts-dai/renovate-config/blob/main/default.json
```
{
"$schema": "https://docs.renovatebot.com/renovate-schema.json",
"extends": [
"config:recommended",
":dependencyDashboard",
"github>tx-pts-dai/renovate-config:automerge-github-actions",
"github>tx-pts-dai/renovate-config:group-github-actions-minor-patch",
"github>tx-pts-dai/renovate-config:group-terraform-minor-patch"
],
"branchPrefix": "renovate_",
"timezone": "Europe/Zurich",
"dependencyDashboardTitle": "Renovate Dashboard",
"suppressNotifications": ["prIgnoreNotification"],
"commitBodyTable": true,
"rebaseWhen": "conflicted",
"platformCommit": true,
"reviewersFromCodeOwners": true,
"prCreation": "immediate",
"enabledManagers": ["dockerfile", "terraform", "github-actions", "circleci"]
}
```
=> feat: Use shared renovate config

.github/workflows/gh-release-on-main.yaml
Renovates PR crashing the WF because containing tables. Example:
```
chore(deps): update tx-pts-dai/github-workflows action to v0.37.0
| datasource  | package                     | from    | to      |
| ----------- | --------------------------- | ------- | ------- |
| github-tags | tx-pts-dai/github-workflows | v0.25.0 | v0.37.0 |
```
This then breaks the ENV vars due to pipe char. More in general it looks good to extract only the first line and avoid special characters. This is where the useful information is.
=> fix: Release wf crashing on renovates PRs

.github/workflows/tf-plan.yaml
renamed github_comment input to be inline with the rest. it has not be used before.
=> fix: add gh artifacts to tf plan workflow

.github/workflows/tf-cleanup.yaml, .github/workflows/tf-feature.yaml
Prevent dangling resources from feature branches. 
Sometimes terraform hangs on destroying some resources due to race conditions. retry normally works.
=> fix: retry terraform workspace destroy workflow if the first try fails

.github/workflows/tf-cleanup.yaml, .github/workflows/tf-destroy.yaml
Dont need to download aws cli again since its already in the workspace and mounted into the container. 
Also added the retry to the tf-destroy workflow
=> fix: update destroy workflows to fail on second attempt

.github/workflows/tf-apply.yaml, .github/workflows/tf-cleanup.yaml, .github/workflows/tf-destroy.yaml, .github/workflows/tf-feature.yaml, .github/workflows/tf-plan.yaml
if the awscli install runs twice, there are conflicting files since the unpack is in the workspace directory
Another option is to install the aws cli bin into the workspace directory and create a dedicated step for required tools. This would need some extra thought so I will implement the simplest solution for now that works
=> fix: add overwrite arg to awscli unzip

.github/workflows/_test-tf.yaml, .github/workflows/tf-apply.yaml, .github/workflows/tf-feature.yaml
This PR adds a way to retrieve terraform outputs for using them in possible next jobs. It also shows a clean and sexy summary of all existing terraform outputs in a json like format. It's then easy for the caller to find one output he needs and can reuse in follow up jobs.
When another job depends on a terraform job, it is useful to have the terraform outputs available for the next job to use and not use some magic to guess the value.
No breaking changes, more features :rocket:
This has been tested adding a couple testing steps. One shows the full output extracted from the shared workflow, the other one shows a specific output value directly extracted from the output json.
See https://github.com/tx-pts-dai/github-workflows/blob/66074b51bd94bffc61f97dda4696c439f20cfb0b/.github/workflows/_te …
=> FUM3284 - Make outputs available

.github/workflows/_test-tf.yaml, .github/workflows/tf-apply.yaml, .github/workflows/tf-feature.yaml, .github/workflows/tf-plan.yaml, tests/terraform/local/main.tf
Add Summary Action
Reuse code where you can and not manage multiple inline bash scripts within the workflows. 
None
=> feat: add summary action

.github/pull_request_template.md, .github/workflows/_test-tf.yaml, .github/workflows/aws-secrets-copy.yaml, .github/workflows/tf-apply.yaml, .github/workflows/tf-cleanup.yaml, .github/workflows/tf-destroy.yaml, .github/workflows/tf-feature.yaml, .github/workflows/tf-plan.yaml, tests/terraform/s3/main.tf
Remove concurrency groups from reusable workflows
it was causing issues in disco where they dont use environments so jobs were getting canceled. The logic is better to have where its needed
Some piplines might run concurrently but this is not an issue for terraform since we use locks
=> feat!: remove concurrency groups and adjust tests

.github/workflows/_test-docker.yaml, .github/workflows/publish-docs.yaml
Docker summary page requires a valid tag to reference
Only deploy pages when needed
=> tests: use valid tag

.github/workflows/_test-tf.yaml, .github/workflows/tf-apply.yaml, .github/workflows/tf-cleanup.yaml, .github/workflows/tf-destroy.yaml, .github/workflows/tf-feature.yaml, .github/workflows/tf-plan.yaml, docs/workflows/tf-apply.md, docs/workflows/tf-cleanup.md, docs/workflows/tf-destroy.md, docs/workflows/tf-feature.md, docs/workflows/tf-plan.md
Allow checkout out a branch with a ref
Allows for trigging a workflow with an issue comment and checking out the branch where the issue (pr comment) was made
=> feat: allow checking out any ref

.github/workflows/docker-build-push-ecr.yaml, .github/workflows/tf-apply.yaml, .github/workflows/tf-feature.yaml, .github/workflows/tf-plan.yaml, docs/workflows/docker-build-push-ecr.md, docs/workflows/tf-apply.md, docs/workflows/tf-feature.md, docs/workflows/tf-plan.md
Add support for artifact features described here https://github.com/actions/download-artifact/tree/fa0a91b85d4f404e444e00e005971372dc801d16/?tab=readme-ov-file#inputs
Introduced inputs are pattern and merge_multiple
Requirements in case multiple artifacts needs to be pushed at different steps of the pipeline
No
=> feat: artifact support pattern and merge_multiple

.github/workflows/_test-tf.yaml, .github/workflows/tf-cleanup.yaml, .github/workflows/tf-destroy.yaml, tests/terraform/s3/main.tf
Error on cleanup/destroy workflows if any errors occur 
If TF init failed the cleanup job would silently error and go unnoticed.
None
=> fix: dont swallow errors on destroy runs

.pre-commit-config.yaml
Update pre-commit packages
pre-commit was failing on MacOS 15.2. Was on "renovate" hook/package.
None
=> chore(pre-commit): update hook packages

README.md
Fix documentation on how to releases on this repo
- README was wrong
- Need to release a new minor version because of the addition of the lambda-python workflow
--> When merging this PR, put "feat: Add Lambda-Python workflow" at the start the message
none
=> doc: document release process

README.md, docs/getting-started/tam-cli.md
Update the references to github repos which have changed
From [FUM-3408](https://tamedia.atlassian.net/browse/FUM-3408), two template repositories are in the process of being transferred from the [tx-pts-dai](https://github.com/tx-pts-dai) to the [DND-IT](https://github.com/DND-IT) organization. This PR align the tam-cli defaults and documentation with those new references
nonw
- [🚫  ] I have updated at least one of the `.github/workflows/_test-*.yaml` to demonstrate and validate my change(s) --> Not applicable
- [✅ ] I have executed `pre-commit run -a` on my pull request
- [✅ ] I have executed `make gen_docs_run` on my pull request --> but it's not working (gen-doc not found)
=> Fum 3408 - move some repos between github organization 

docs/.scripts/gen_docs/bin/index.js, docs/workflows/aws-secrets-copy.md, docs/workflows/docker-build-push-ecr.md, docs/workflows/docker-build.md, docs/workflows/docker-push-ecr.md, docs/workflows/gh-release-on-main.md, docs/workflows/gh-release.md, docs/workflows/lambda-build-node.md, docs/workflows/lambda-nodejs.md, docs/workflows/lambda-python.md, docs/workflows/tf-apply.md, docs/workflows/tf-cleanup.md, docs/workflows/tf-destroy.md, docs/workflows/tf-feature.md, docs/workflows/tf-plan.md
Update the doc with last major release of the repo (v2 instead of v1)
The documentation (see https://tx-pts-dai.github.io/github-workflows/workflows/tf-apply/ for examle) is still referring v1 of the workflow, this PR fix it
And some change to  the indentation of the headers to make markdown linter more happy
(I removed the `action-doc-header` in the template because it's exactly the same as the workflowName in the title)
None, it's only a change in the documentation
=> doc: update header indentation

.github/workflows/_test-tf.yaml, .github/workflows/tf-cleanup.yaml, tests/terraform/s3/test.tfbackend
This PR adds a check that verifies if the terraform workspace exists before running the dflook destroy-workspace workflow.
The dflook workflow currently breaks if the workspace doesn't exist.
For context: it seems that dflook is willing to consider adding the check directly in his own action: https://github.com/dflook/terraform-github-actions/issues/368
None
=> fix: [tf-cleanup] check if workspace exists
